### DISCUSSION TITLE
How to config LOCAL_TEMP_FILE_PATH

### DISCUSSION THREAD

**Discussion by krau** [simonsmh/telegram-bili-feed-helper#43] [Q&A] [answered]
I'm using docker-compose to run biliparser and telegram-bot-api instance, the compose file like this:

```yml
services:
  biliparser:
    build:
      context: .
    container_name: biliparser
    env_file:
      - .env
    restart: unless-stopped
  api:
    restart: always
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ""
      TELEGRAM_API_HASH: ""
      TELEGRAM_STAT: 1
      TELEGRAM_VERBOSITY: 1
      TELEGRAM_LOCAL: 1
    volumes:
      - ./apidata:/var/lib/telegram-bot-api
```

In this case, how do i config `LOCAL_TEMP_FILE_PATH` correctly?

I tried some values but all cause error `"__main__:parse:456 - Can't find real file path"`
